# ----------------------------------------
# Created on: Fri Oct 20 16:49:54 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 fifo_tb usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
