# ----------------------------------------
# Created on: Fri Oct 20 16:49:54 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/usim"
vmap  adc "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/adc"
vmap  ddrc "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/ddrc"
vmap  ddrphy "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/ddrphy"
vmap  hsst_e2 "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/hsst_e2"
vmap  iolhr_dft "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/iolhr_dft"
vmap  ipal_e1 "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/ipal_e1"
vmap  pciegen2 "C:/Users/JIAOFUJUN/Desktop/scaler_version/compile/pciegen2"
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/hdmi_ddr_ov5640_top.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/cmos_8_16bit.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/i2c_com.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/iic_dri.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/ms72xx_ctl.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/ms7200_ctl.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/ms7210_ctl.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/power_on_delay.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/reg_config.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/frame_fifo_read.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/frame_fifo_write.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/frame_read_write.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/mem_read_arbi.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/mem_write_arbi.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/aq_axi_master_256.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/color_bar.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/timing_gen_xy.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/video_define.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/cmos_tailor.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/SCALE_DOWN/calu.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/SCALE_DOWN/scale_top.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/SCALE_DOWN/scaler.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/SCALE_DOWN/vin_scale_down.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/SCALE_DOWN/change_param.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/hdmi_in_1920_to_960.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DDR3/write_req_gen.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/DISPLAY/video_rect_read_data.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/btn_deb_fix.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/key_ctl.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/scaler_up.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/yuv.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/lighter_and_color.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/gs_filter.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/line_shift.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/Matrix_3X3.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/sobel_test.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/pll/pll.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/DDR3_50H.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/DDR3_50H_ddrphy_top.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ipsxb_rst_sync_v1_1.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_calib_mux_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_calib_top_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_control_path_adj_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_data_slice_v1_4.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_data_slice_dqs_gate_cal_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_data_slice_wrlvl_v1_4.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_dfi_v1_4.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_dll_update_ctrl_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_dqsi_rdel_cal_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_dqs_gate_coarse_cal_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_dqs_rddata_align_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_drift_ctrl_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_gate_update_ctrl_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_gatecal_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_info_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_init_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_main_ctrl_v1_3.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_rdcal_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_reset_ctrl_v1_4.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_rst_debounce_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_slice_rddata_align_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_training_ctrl_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_upcal_v1_4.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_wdata_path_adj_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_wrlvl_v1_0.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/ddrphy/ipsxb_ddrphy_slice_top_v1_4.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/pll/ipsxb_ddrphy_pll_v1_0.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_apb_cross_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_calib_delay_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_cfg_apb_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_bm_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_rowaddr_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_sm_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_top_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_back_ctrl_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_buf_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_out_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_top_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_dfi_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_lp_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_mrs_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_prefetch_fifo_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_rdatapath_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_reg_fifo2_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_ui_axi_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_wdatapath_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_align_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_dcp_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/ipsxb_mcdq_wrapper_v1_2a.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_com_timing_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_timing_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act2wr_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_pre_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_rd_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_ref_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_wr_pass_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_trc_timing_v1_2.vp" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/distributed_fifo/ipsxb_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/rtl/DDR3_50H/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_sdpram_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_16i_64o_512/rtl/ipml_sdpram_v1_6_afifo_16i_64o_512.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_v1_6_afifo_16i_64o_512.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_16i_64o_512/afifo_16i_64o_512.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_64i_16o_128/rtl/ipml_sdpram_v1_6_afifo_64i_16o_128.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_v1_6_afifo_64i_16o_128.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/afifo_64i_16o_128/afifo_64i_16o_128.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/hdmi_linebuffer/rtl/ipml_sdpram_v1_6_hdmi_linebuffer.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/hdmi_linebuffer/hdmi_linebuffer.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo/rtl/ipml_sdpram_v1_6_fifo.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo/rtl/ipml_fifo_v1_6_fifo.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo/fifo.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/ram_scaler/rtl/ipml_sdpram_v1_6_ram_scaler.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/ram_scaler/ram_scaler.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo_shift/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo_shift/rtl/ipml_sdpram_v1_6_fifo_shift.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo_shift/rtl/ipml_fifo_v1_6_fifo_shift.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/ipcore/fifo_shift/fifo_shift.v" -work work
vlog   "C:/Users/JIAOFUJUN/Desktop/scaler_version/source/fifo_tb.v" -work work

# ----------------------------------------
